---
- hosts: kubernetes-worker-nodes
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=/root/join_token

  - name: Joining worker nodes with kubernetes master
##    shell: "`grep -i 'kubeadm join' /root/join_token `--ignore-preflight-errors=all "
    shell: "`grep -i 'kubeadm join' /root/join_token `"
